#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

Options=" -o StrictHostKeyChecking=no"

if [ -z "$PATH_TO_SSH_KEY" ]; then
	scp "$Options" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
else
	scp "$Options" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~
fi
