#!/usr/bin/env bash
#Install nginx

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

REDIRECTION="
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
"

sudo sed -i "/location \/ {/a $REDIRECTION" /etc/nginx/sites-available/default

sudo service nginx restart
