#!/usr/bin/env bash
#Install & Configure Nginx server to have a custom 404 page
#that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

REDIRECTION="\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }"

sudo sed -i "53s|.*|$REDIRECTION|" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
