#!/usr/bin/env bash
#Install & Configure Nginx server to have a custom 404 page
#that contains the string Ceci n'est pas une page
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

REDIRECTION=$(cat <<EOF
                add_header X-Served-By '$(hostname)';

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /custom_404.html;

        location /custom_404.html {
                root /var/www/html;
        }
EOF
)

sudo sed -i '/^server {/r /dev/stdin' /etc/nginx/sites-enabled/default <<< "$REDIRECTION"

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo nginx -t
sudo service nginx restart
