#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

cat <<EOF |sudo tee /etc/haproxy/haproxy.conf
global
	log /dev/log local0
    	log /dev/log local1 notice
    	maxconn 2000
    	user haproxy
    	group haproxy

defaults
    	log global
    	mode http
    	option httplog
    	option dontlognull
    	timeout connect 5000
    	timeout client 50000
    	timeout server 50000

frontend main
    	bind *:80
    	default_backend web_servers

backend we_servers
	server 323649-web-01 100.26.178.116:80
	server 323649-web-02 54.144.154.1:80
	balance roundrobin
EOF

sudo haproxy -c -f /etc/haproxy/haproxy.conf

sudo service haproxy restart
