#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

echo "
backend we_servers
	server 323649-web-01 100.26.178.116:80
	server 323649-web-02 54.144.154.1:80
	balance roundrobin" >> /etc/haproxy/haproxy.cfg

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
