#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

echo "
frontend http-in
        bind *:80
        default_backend web_servers

backend web_servers
        server 323649-web-01 100.26.178.116:80 check
        server 323649-web-02 54.144.154.1:80 check
        balance roundrobin
" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
