#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

PFILE="/var/run/my_process.pid"

case "$1" in
	"start")
		./manage_my_process & echo $! > "$PFILE"
		echo "manage_my_process started"
		;;
	"stop")
		PID=$(cat "$PFILE")
		kill "$PID"
		rm -f "$PFILE"
		echo "manage_my_process stopped"
		;;

	"restart")
		PID=$(cat "$PFILE")
		kill "$PID"
		rm -f "$PFILE"
		./manage_my_process & echo $! > "$PFILE"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

exit 0
