#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

PFILE="/var/run/my_process.pid"

case "$1" in
	"start")
		if [ -f "$PFILE" ];
		then
			echo "Error: manage_my_process is already running."
		else
			./manage_my_process & echo $! > "$PFILE"
			echo "manage_my_process started"
		fi
		;;
	"stop")
		if [ -f "$PFILE" ];
		then
			PID=$(cat "$PFILE")
			kill "$PID"
			rm -f "$PFILE"
			echo "manage_my_process stopped"
		else
			echo "Error: manage_my_process is not running."
		fi
		;;

	"restart")
		if [ -f "$PFILE" ];
		then
			PID=$(cat "$PFILE")
			kill "$PID"
			rm -f "$PFILE"
		fi
		./manage_my_process & echo $! > "$PFILE"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
