#!/usr/bin/env bash
# Bash script that displays the content of the file
# /etc/passwd, using the while loop + IFS.

IFS=":"
while read -r usrname pass u_id g_id u_info home_dir cmd;
do
	echo "The user $usrname is part of the $g_id gang, lives in $home_dir and rides $cmd. $u_id's place is protected by the passcode $pass, more info about the user here: $u_info"
done < /etc/passwd
