#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
sed -i "s/^127.*/172.0.0.2	localhost/" ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
